STAFF_PERMISSIONS = [
    'add_cognitionmemoryskillsgoals',
    'change_cognitionmemoryskillsgoals',
    'add_cognitivememoryskillsassessment',
    'change_cognitivememoryskillsassessment',
    'add_communicationassessment',
    'change_communicationassessment',
    'add_communicationgoals',
    'change_communicationgoals',
    'add_motorskillsassessment',
    'change_motorskillsassessment',
    'add_motorskillsgoals',
    'change_motorskillsgoals',
    'add_musicalpreference',
    'change_musicalpreference',
    'add_musicskillsassessment',
    'change_musicskillsassessment',
    'add_musicskillsgoals',
    'change_musicskillsgoals',
    'add_observablebehaviours',
    'change_observablebehaviours',
    'add_psychosocialassessment',
    'change_psychosocialassessment',
    'add_psychosocialgoals',
    'change_psychosocialgoals',
    'add_socialskillsassessment',
    'change_socialskillsassessment',
    'add_socialskillsgoals',
    'change_socialskillsgoals',
]

ADMIN_PERMISSIONS = STAFF_PERMISSIONS + ['add_user', 'change_user', 'add_userinfo', 'change_userinfo']
